AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Related resources for a DynamoDB table

Parameters:
  StackName:
    Type: String
    Default: none

  TableName:
    Type: String
    Default: none

  TableArn:
    Type: String

Resources:
  TableReadManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:ConditionCheckItem
              - dynamodb:DescribeTable
            Resource:
              - !Ref TableArn
              - !Sub ${TableArn}/index/*
      Roles:
        - !Ref TableReadWriteRole

  TableWriteManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:BatchWriteItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource:
              - !Ref TableArn
              - !Sub ${TableArn}/index/*
      Roles:
        - !Ref TableReadWriteRole

  TableReadWriteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${StackName}-datastore
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::591291862413:role/*"
            Action: sts:AssumeRole

Outputs:
  TableReadPolicyArn:
    Description: Table read policy arn
    Value: !GetAtt TableReadManagedPolicy.PolicyArn
    Export:
      Name: !Sub ${StackName}:tables:${TableName}:TableReadPolicyArn

  TableReadPolicyId:
    Description: Table read policy id
    Value: !GetAtt TableReadManagedPolicy.PolicyId

  TableWritePolicyArn:
    Description: Table write policy arn
    Value: !GetAtt TableWriteManagedPolicy.PolicyArn
    Export:
      Name: !Sub ${StackName}:tables:${TableName}:TableWritePolicyArn

  TableWritePolicyId:
    Description: Table write policy id
    Value: !GetAtt TableWriteManagedPolicy.PolicyId
