AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DDB POC DynamoDB tables and related resources

Parameters:
  StackName:
    Type: String
    Default: none

Resources:
  DynamoDbPocKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: key-ddb-poc
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"

  DynamoDbPocKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${StackName}-DynamoDbPocKMSKeyAlias
      TargetKeyId: !Ref DynamoDbPocKMSKey

  DynamoDbPocTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${StackName}-DynamoDbPoc
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: nhsNumber
          AttributeType: S
        - AttributeName: creationDatetime
          AttributeType: S
        - AttributeName: prescriberOrg
          AttributeType: S
        - AttributeName: dispenserOrg
          AttributeType: S
        - AttributeName: nominatedPharmacy
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: nextActivity
          AttributeType: S
        - AttributeName: nextActivityDate
          AttributeType: S
        - AttributeName: docRefTitle
          AttributeType: S
        - AttributeName: storeTime
          AttributeType: S
        - AttributeName: backstopDeleteDate
          AttributeType: S
        - AttributeName: prescriptionId
          AttributeType: S
        - AttributeName: sequenceNumber
          AttributeType: N
        - AttributeName: sequenceNumberNwssp
          AttributeType: N

      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        KMSMasterKeyId: !Ref DynamoDbPocKMSKey
        SSEEnabled: true
        SSEType: KMS
      GlobalSecondaryIndexes:
        - IndexName: nhsNumberDate
          KeySchema:
            - AttributeName: nhsNumber
              KeyType: HASH
            - AttributeName: creationDatetime
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - indexes
              - prescriberOrg
              - dispenserOrg
        - IndexName: prescriberDate
          KeySchema:
            - AttributeName: prescriberOrg
              KeyType: HASH
            - AttributeName: creationDatetime
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - indexes
              - dispenserOrg
        - IndexName: dispenserDate
          KeySchema:
            - AttributeName: dispenserOrg
              KeyType: HASH
            - AttributeName: creationDatetime
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - indexes
        - IndexName: nominatedPharmacyStatus
          KeySchema:
            - AttributeName: nominatedPharmacy
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - indexes
        - IndexName: claimId
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - claimIds
        - IndexName: nextActivityDate
          KeySchema:
            - AttributeName: nextActivity
              KeyType: HASH
            - AttributeName: nextActivityDate
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: storeTimeDocRefTitle
          KeySchema:
            - AttributeName: docRefTitle
              KeyType: HASH
            - AttributeName: storeTime
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: backstopDeleteDate
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: backstopDeleteDate
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: prescriptionId
          KeySchema:
            - AttributeName: prescriptionId
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: claimIdSequenceNumber
          KeySchema:
            - AttributeName: sequenceNumber
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: claimIdSequenceNumberNwssp
          KeySchema:
            - AttributeName: sequenceNumberNwssp
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  DynamoDbPocResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamodb_resources.yaml
      Parameters:
        StackName: !Ref StackName
        TableName: !Ref DynamoDbPocTable
        TableArn: !GetAtt DynamoDbPocTable.Arn

Outputs:
  DynamoDbPocTableName:
    Description: DynamoDB POC table name
    Value: !Ref DynamoDbPocTable

  DynamoDbPocTableArn:
    Description: DynamoDB POC table arn
    Value: !GetAtt DynamoDbPocTable.Arn
