AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Datastore tables and related resources

Parameters:
  StackName:
    Type: String
    Default: none

Resources:
  DatastoreKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: key-spine-eps
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"

  DatastoreKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${StackName}-DatastoreKMSKeyAlias
      TargetKeyId: !Ref DatastoreKMSKey

  DatastoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${StackName}-datastore
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: nhsNumber
          AttributeType: S
        - AttributeName: creationDatetime
          AttributeType: S
        - AttributeName: prescriberOrg
          AttributeType: S
        - AttributeName: dispenserOrg
          AttributeType: S
        - AttributeName: nominatedPharmacy
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: nextActivity
          AttributeType: S
        - AttributeName: nextActivityDate
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        KMSMasterKeyId: !Ref DatastoreKMSKey
        SSEEnabled: true
        SSEType: KMS
      GlobalSecondaryIndexes:
        - IndexName: nhsNumberDate
          KeySchema:
            - AttributeName: nhsNumber
              KeyType: HASH
            - AttributeName: creationDatetime
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - indexes
              - prescriberOrg
              - dispenserOrg
        - IndexName: prescriberDate
          KeySchema:
            - AttributeName: prescriberOrg
              KeyType: HASH
            - AttributeName: creationDatetime
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - indexes
              - dispenserOrg
        - IndexName: dispenserDate
          KeySchema:
            - AttributeName: dispenserOrg
              KeyType: HASH
            - AttributeName: creationDatetime
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - indexes
        - IndexName: nominatedPharmacyStatus
          KeySchema:
            - AttributeName: nominatedPharmacy
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - indexes
        - IndexName: claimId
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - claimIds
        - IndexName: nextActivityDate
          KeySchema:
            - AttributeName: nextActivity
              KeyType: HASH
            - AttributeName: nextActivityDate
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY

  DatastoreResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamodb_resources.yaml
      Parameters:
        StackName: !Ref StackName
        TableName: !Ref DatastoreTable
        TableArn: !GetAtt DatastoreTable.Arn

Outputs:
  DatastoreTableName:
    Description: Datastore table name
    Value: !Ref DatastoreTable

  DatastoreTableArn:
    Description: Datastore table arn
    Value: !GetAtt DatastoreTable.Arn
