name: Package and upload code

on:
  workflow_call:

jobs:
  package_code:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH_NAME}}

      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.11.3
  
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: ~/.asdf
          key: ${{runner.os}}-asdf-${{hashFiles('**/.tool-versions')}}
          restore-keys: ${{runner.os}}-asdf-

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.11.3
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared
      
      - name: Run make install
        run: make install

      - shell: bash
        name: Package code
        run: |
          cp .tool-versions ~/
          rm -rf .aws-sam
          make sam-build
          cp Makefile .aws-sam/build/
          cp samconfig_package_and_deploy.toml .aws-sam/build/

      - uses: actions/upload-artifact@v4
        name: Upload build artifact
        with:
          name: packaged_code
          path: |
            .aws-sam/build
            README.md
            
      - uses: actions/upload-artifact@v4
        name: Upload python dependency files
        with:
          name: python_dependency_files
          path: |
            .tool-versions
            poetry.lock
            poetry.toml
            pyproject.toml
